server:
  port: 5000
spring:
  application:
    name: peng-crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: localhost
    password: 123456
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI4FtyK7WcqxaiE9ttukNi
    access-key-secret: 43OFOgMghjsitNsNlTGqcpPGgyzqgU
    bucket-domain: http://peng190830.oss-cn-shenzhen.aliyuncs.com
    bucket-name: peng190830
    end-point: http://oss-cn-shenzhen.aliyuncs.com