server:
  port: 3000
spring:
  application:
    name: peng-crowd-redis
  redis:
    host: localhost
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka